import type { InventoryItem, LandObject, LandSummary } from "./types";

export const MY_WALLET = "0x1A2B3C4D5E6F7890ABCDEF1234567890ABCDEF3C4D";
export const MY_SHORT = "0x1A2B…3C4D";

export const PLACED_OBJECTS: LandObject[] = [
  {
    id: "obj-jup",
    gx: 1,
    gy: 2,
    hue: 30,
    glyph: "J",
    type: "tower",
    name: "Jupiter Power User",
    protocol: "Jupiter",
    tile: "B-3",
    mintedAt: "2026-04-12",
  },
  {
    id: "obj-drift",
    gx: 4,
    gy: 1,
    hue: 240,
    glyph: "D",
    type: "crystal",
    name: "Drift Degen",
    protocol: "Drift",
    tile: "E-2",
    mintedAt: "2026-03-28",
  },
  {
    id: "obj-jito",
    gx: 2,
    gy: 5,
    hue: 140,
    glyph: "J",
    type: "tree",
    name: "Jito Staker",
    protocol: "Jito",
    tile: "C-6",
    mintedAt: "2026-04-02",
  },
  {
    id: "obj-meteora",
    gx: 5,
    gy: 4,
    hue: 80,
    glyph: "M",
    type: "dome",
    name: "Meteora LP",
    protocol: "Meteora",
    tile: "F-5",
    mintedAt: "2026-04-18",
  },
  {
    id: "obj-me",
    gx: 3,
    gy: 3,
    hue: 320,
    glyph: "E",
    type: "mushroom",
    name: "Magic Eden Minter",
    protocol: "Magic Eden",
    tile: "D-4",
    mintedAt: "2026-02-11",
  },
  {
    id: "obj-sol",
    gx: 6,
    gy: 2,
    hue: 180,
    glyph: "S",
    type: "shrine",
    name: "Solana OG",
    protocol: "Solana",
    tile: "G-3",
    mintedAt: "2025-12-05",
  },
  {
    id: "obj-kamino",
    gx: 0,
    gy: 6,
    hue: 200,
    glyph: "K",
    type: "lighthouse",
    name: "Kamino Lender",
    protocol: "Kamino",
    tile: "A-7",
    mintedAt: "2026-01-14",
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: "inv-jup",
    glyph: "J",
    label: "Jupiter",
    protocol: "Jupiter",
    name: "Jupiter Power User",
    hue: 30,
    type: "tower",
    state: "placed",
  },
  {
    id: "inv-drift",
    glyph: "D",
    label: "Drift",
    protocol: "Drift",
    name: "Drift Degen",
    hue: 240,
    type: "crystal",
    state: "placed",
  },
  {
    id: "inv-jito",
    glyph: "J",
    label: "Jito",
    protocol: "Jito",
    name: "Jito Staker",
    hue: 140,
    type: "tree",
    state: "placed",
  },
  {
    id: "inv-meteora",
    glyph: "M",
    label: "Meteora",
    protocol: "Meteora",
    name: "Meteora LP",
    hue: 80,
    type: "dome",
    state: "placed",
  },
  {
    id: "inv-raydium",
    glyph: "R",
    label: "Raydium",
    protocol: "Raydium",
    name: "Raydium LP",
    hue: 0,
    type: "crystal",
    state: "eligible",
  },
  {
    id: "inv-kamino",
    glyph: "K",
    label: "Kamino",
    protocol: "Kamino",
    name: "Kamino Lender",
    hue: 200,
    type: "lighthouse",
    state: "eligible",
    isNew: true,
  },
  {
    id: "inv-marinade",
    glyph: "M",
    label: "Marinade",
    protocol: "Marinade",
    name: "Marinade mSOL",
    hue: 160,
    type: "mushroom",
    state: "eligible",
  },
  {
    id: "inv-orca",
    glyph: "O",
    label: "Orca",
    protocol: "Orca",
    name: "Orca Pool Maker",
    hue: 190,
    type: "dome",
    state: "eligible",
    isNew: true,
  },
];

export const LAND_DIRECTORY: LandSummary[] = [
  {
    address: "0x1A2B…3C4D",
    displayName: "you.sol",
    objectsCount: 27,
    points: 2140,
    rank: 1,
    seed: 1,
    featured: true,
    rarityPct: 1,
  },
  {
    address: "0xBEEF…0001",
    objectsCount: 21,
    points: 1240,
    rank: 12,
    seed: 2,
  },
  {
    address: "0x3A77…EF02",
    objectsCount: 17,
    points: 980,
    rank: 28,
    seed: 4,
  },
  {
    address: "0x9F87…22E1",
    objectsCount: 9,
    points: 540,
    rank: 91,
    seed: 3,
    badge: "RISING",
  },
  {
    address: "0x5C5C…9A9A",
    objectsCount: 12,
    points: 710,
    rank: 47,
    seed: 7,
  },
  {
    address: "0x1111…2222",
    objectsCount: 4,
    points: 180,
    rank: 204,
    seed: 6,
  },
  {
    address: "0xDEAD…CA11",
    objectsCount: 6,
    points: 310,
    rank: 158,
    seed: 5,
  },
  {
    address: "0x4242…4242",
    objectsCount: 8,
    points: 420,
    rank: 122,
    seed: 8,
  },
];

export const LIVE_TICKER = [
  { addr: "0x3A77…EF02", action: "minted", target: "Jupiter Power User" },
  { addr: "0xBEEF…0001", action: "placed", target: "Magic Eden Minter" },
  { addr: "0x9F87…22E1", action: "reached", target: "rank #91" },
];

export const STATS = {
  protocols: 7,
  transactions: 1284,
  points: 820,
  objects: 7,
  eligible: 4,
  mintedTotal: 12483,
  today: 47,
};

export const tileLabel = (gx: number, gy: number) =>
  `${String.fromCharCode(65 + gx)}-${gy + 1}`;
